### ISSUE TITLE
main page에서 게임 랭킹 리스트 필요합니다!

### ISSUE THREAD

**Issue by nes03007** [KIT-Minions/game_recommandation_front#11]
1위부터 20위까지의 게임 리스트 불러오는 api 만들어주세요!

**Comment by grapgrap** [comment]
@nes03007 wiki 다시 보고 와라 애송아

https://github.com/KIT-Minions/game_recommandation_back/wiki/%EA%B2%8C%EC%9E%84-%ED%8F%89%EC%A0%90-%EA%B4%80%EB%A0%A8-API_-%EB%9E%AD%ED%82%B9

**Comment by nes03007** [comment]
쿠쿸....
