### ISSUE TITLE
게임 상세 페이지 api

### ISSUE THREAD

**Issue by gagahwahwa** [KIT-Minions/game_recommandation_front#12]
게임 상세 페이지에서 게임 제조사랑 게임 제조일자 부분이 없는것 같아요....

**Comment by gagahwahwa** [comment]
해당 게임의 태그도,,,.?

**Comment by grapgrap** [comment]
https://github.com/KIT-Minions/game_recommandation_back/wiki/%EA%B2%8C%EC%9E%84-%EC%A0%95%EB%B3%B4

추가 완료

**Comment by grapgrap** [comment]
@gagahwahwa 태그는 추가되는 데로 다시 알려주겠음

**Comment by grapgrap** [comment]
불편하면 두 API를 합치겠음
