### ISSUE TITLE
댓글 출력시 평점 바 문제

### ISSUE THREAD

**Issue by guswjd7104** [KIT-Minions/game_recommandation_front#13]
댓글 리스트의 평점바가 마우스 오버 및 클릭시 값이 바뀜

**Comment by grapgrap** [comment]
98cc7fef238fc3ac516f305ebc5e89ee66d9aff6

star rate에 readOnly 속성 추가
값이 바뀌면 안되는 곳에 
`[readOnly]='true'` 추가하면 됨
